### ISSUE TITLE
Prevent program crashes when input is missing

### ISSUE THREAD

**Issue by TheSlimvReal** [TheSlimvReal/PSE---LA-meets-ML#212]
Running the collector without a provided name results in a crash of the program. This should not happen. The other commands should also be checked if similar behavior can happen there too.

**Comment by annaric** [comment]
It is now possible to type the input without the name but come commands still dont work without the path (classify, train)

**Comment by TheSlimvReal** [comment]
A wrong or missing path should still not result in a program crash but in a usefull help message together with a controlled shut down if the config file is set up incorrect.
