### ISSUE TITLE
Error handling on loader/saver

### ISSUE THREAD

**Issue by TheSlimvReal** [TheSlimvReal/PSE---LA-meets-ML#227]
When using the loader or saver, they should raise an IOException if something went wrong. 
Every usage of them should therefore be in a sepcial try/except block to make sure the file got correctly loaded.
This step is important so we don't have program crashes on incorrect inputs/config file configurations.

**Comment by annaric** [comment]
@yannickfunk as you are implementing the loader, can you also assign this task to you?
