### ISSUE TITLE
Collect required technologies

### ISSUE THREAD

**Issue by TheSlimvReal** [TheSlimvReal/PSE---LA-meets-ML#3]
Make a list of all required/preferred technologies along with some documenation or tutorial links that help to get started.

**Comment by yannickfunk** [comment]
My suggested list would be:

process model: SCRUM
- https://en.wikipedia.org/wiki/Scrum_(software_development)
- Softwaretechnik 1 slides SS18
- use a tool to coordinate the processes

design: UML
- https://en.wikipedia.org/wiki/Unified_Modeling_Language
- Softwaretechnik 1 slides SS18
- class diagrams, sequence diagrams, etc...

programming language: Python 3
- https://wiki.python.org/moin/BeginnersGuide
- ask me to get access to a German Python course on Udemy
- https://realpython.com/python3-object-oriented-programming/

documentation: Doxygen
- http://www.stack.nl/~dimitri/doxygen/manual/index.html
- https://en.wikipedia.org/wiki/Doxygen

testing: Python built-in unit tests
- https://docs.python.org/3/library/unittest.html

machine learning: Keras
- https://keras.io/
- https://www.youtube.com/watch?v=J6Ok8p463C4 (Google Intro)
- https://www.youtube.com/watch?v=j_pJmXJwMLA&t=11s (Siraj Raval - Keras Explained)

linear algebra: Ginkgo
-  https://github.com/ginkgo-project/ginkgo

If everybody agrees with that list, it should be formatted to markdown and pushed on the repo
