### ISSUE TITLE
Random thoughts

### ISSUE THREAD

**Issue by Eoli-an** [TheSlimvReal/PSE---LA-meets-ML#32]
I made a list of things that stood out to me while working on the specification sheet. I´d love if we could discuss them.

*Is it usefull to let the user decide how he wants to split the training and test data? Since he can not change any of the other hyperparamters it seems out of place

*Why is user able to specify a path to safe the neural network to, but he can not specify a path to safe the matricies and labeld greyscale pattern images(maybe default results folder for every module)

*if the user only wants to use our classifier it might be reasonable to let him use our nn and not worry about specifing a path where the nn is in the file system.

*When someone uses the classifier and when someone uses the labling module a greayscale pattern image conversion has to be done. Would it make sense to create another module for the greyscale pattern image?

*we could add a "durchführbarkeitsanalyse" (similar work has been done by our supervisors, there a many preexisting libaries)

* since the "tipps" includes explaining our product we might want to add a page of explaination for the problem we want to solve(what are iterative solvers, why is our work usefull...)

*We each should review the work someone else has done

**Comment by TheSlimvReal** [comment]
I put the optional path flag into every command now and also set the neural network path to be optional in the classifier.
